# Generated by Django 4.2 on 2024-07-29 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRheo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencia',
            old_name='descripcion',
            new_name='descripcion_experiencia',
        ),
        migrations.RenameField(
            model_name='experiencia',
            old_name='nombre',
            new_name='nombre_experiencia',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='fecha_inicio',
        ),
    ]
