# Generated by Django 4.2 on 2024-07-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRheo', '0002_rename_descripcion_experiencia_descripcion_experiencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='nombre',
            new_name='nombre_servicio',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='descripcion',
        ),
    ]
